// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycdpvoxhvgxekdyxtzah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljZHB2b3hodmd4ZWtkeXh0emFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTkzMjQsImV4cCI6MjA3Mjg5NTMyNH0.zaWRf3oILxnFNL_kvnEhSrGzpubNmHMY3BAUKzZ78lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});